cluster_name              = "devops2go-k3s-lab"
hcloud_token              = ""
location                  = "ash"
network_region            = "us-east"
node_type                 = "cpx31"
control_plane_server_type = "cpx21"
